<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
<?php if ($block->getWishlistHelper()->isAllow()) : ?>
    <a href="#"
       class="action towishlist <?= $block->getProduct()->getTypeId() ?>"
       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       role="button"
       data-product="<?= $block->getProduct()->getEntityId() ?>"
       data-name="<?= $block->getProduct()->getName() ?>"
    ></a>
<?php endif; ?>
