<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>
<div class="col col-sm-6 col-md-half col-lg-6">
    <form class="form contact"
          action="<?= $block->escapeUrl($block->getFormAction()) ?>"
          id="contact-form"
          method="post"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>
        <fieldset class="fieldset">
            <div class="field note no-label">
                <?= $block->escapeHtml(__('Jot us a note and we’ll get back to you as quickly as possible.')) ?>
            </div>
            <div class="field name required">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name"
                           id="name"
                           title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                           value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
                           class="input-text"
                           type="text"
                           data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email"
                           id="email"
                           title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                           value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                           class="input-text"
                           type="email"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field telephone">
                <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Telephone')) ?></span></label>
                <div class="control">
                    <input name="telephone-preview"
                           id="telephone-preview"
                           title="<?= $block->escapeHtmlAttr(__('Telephone')) ?>"
                           value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                           class="input-text"
                           type="tel" />
                    <input hidden name="telephone" id="telephone" value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>">
                </div>
            </div>
            <div class="field comment required">
                <label class="label" for="comment">
                    <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span>
                </label>
                <div class="control">
                    <textarea name="comment"
                              id="comment"
                              placeholder="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                              class="input-text"
                              cols="5"
                              rows="3"
                              data-validate="{required:true}"></textarea>
                </div>
            </div>
            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>
<script type="text/javascript">
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        let tel = document.querySelector("#telephone-preview"),
            telSubmit = document.querySelector("#telephone"),
            iti = window.intlTelInput(tel, ({
                preferredCountries: ['sv'],
                initialCountry: 'sv',
                separateDialCode: true
            }));

        function bindPhones() {
            let country = iti.getSelectedCountryData();
            telSubmit.value = `+${country.dialCode} ${tel.value}`;
        }

        tel.addEventListener("countrychange", bindPhones);
        tel.addEventListener("keydown", bindPhones);
        tel.addEventListener("keyup", bindPhones);
    });
</script>
