<?php
// @codingStandardsIgnoreFile
/** @var  $block \Ls\Customer\Block\Order\Info */

use Magento\Framework\Data\Helper\PostHelper;

/**
 * @var \Bananacode\Kip\Block\Main $kip
 */
$kip = $block->getLayout()->createBlock('Bananacode\Kip\Block\Main');

?>
<div class="actions">
    <?php
    $_order = $block->getOrder();
    $magOrder = $kip->getMagOrderFromLsDocumentId($_order->getCustomerOrderNo());
    if (!empty($magOrder)) { ?>
        <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($magOrder->getEntityId())) : ?>
            <a href="#" data-post='<?php /* @escapeNotVerified */
            echo
            $this->helper(PostHelper::class)
                ->getPostData($block->getReorderUrl($magOrder))
            ?>' class="action order">
                <span><?= /* @escapeNotVerified */
                    __('Reorder') ?></span>
            </a>
        <?php endif ?>
        <a class="action print"
           href="<?= /* @escapeNotVerified */
           $block->getPrintUrl($_order) ?>"
           onclick="this.target='_blank';">
            <span><?= /* @escapeNotVerified */
                __('Print Order') ?></span>
        </a>
        <?= $block->getChildHtml() ?>
    <?php } ?>
</div>
