<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div style="background-color: #33BE81; color: white; width: auto; padding: 30px; height: 100vh; text-align: center">
    <h1>Servicio Temporalmente No Disponible</h1>
    <p>
        Kip no puede atender temporalmente tu solicitud debido a un mantenimiento programado.
        Por favor, inténtalo de nuevo más tarde.
    </p>
</div>
<style>
    .page-main {
        padding: 0;
    }
</style>

