<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}

/**
 * @var \Bananacode\Kip\Block\Main $kip
 */
$kip = $block->getLayout()->createBlock('Bananacode\Kip\Block\Main');
$presentacion = $kip->getPresentacion($_product)
?>

<?php if ($_attributeValue) :?>
    <div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
        <?php if ($block->escapeHtmlAttr($_className) === 'overview' && $_product->getTypeId() !== 'grouped' && is_string($presentacion)) :?>
            <div class="value"><?= /* @noEscape */ $presentacion ?></div>
        <?php else: ?>
            <?php if ($renderLabel) :?>
                <strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
            <?php endif; ?>
            <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div>
        <?php endif; ?>
    </div>
<?php else: ?>
    <?php if ($block->escapeHtmlAttr($_className) === 'overview' && $_product->getTypeId() !== 'grouped' && is_string($presentacion)) :?>
        <div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
            <div class="value"><?= /* @noEscape */ $presentacion ?></div>
        </div>
    <?php endif; ?>
<?php endif; ?>
