<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block Magento\Checkout\Block\Onepage\Success
 */
/**
 * @var \Bananacode\Kip\Block\Main $kip
 */
$kip = $block->getLayout()->createBlock('Bananacode\Kip\Block\Main');
$star = '<svg xmlns="http://www.w3.org/2000/svg" width="36" height="32" viewBox="0 0 36 32">
            <g fill="none" fill-rule="evenodd">
                <path d="M0 0h36v32H0z"/>
                <path fill="#9C9793" d="M34.2 12.008c0 .286-.173.599-.519.937l-7.242 6.912 1.716 9.763c.013.091.02.221.02.39 0 .274-.07.505-.21.694-.14.188-.342.283-.609.283-.252 0-.518-.078-.798-.235L17.6 26.144l-8.958 4.608c-.293.157-.56.235-.798.235-.28 0-.49-.095-.629-.283-.14-.19-.21-.42-.21-.694 0-.078.014-.208.04-.39l1.716-9.763L1.5 12.945c-.333-.351-.499-.664-.499-.937 0-.482.372-.78 1.117-.898l10.016-1.425L16.623.8C16.874.267 17.2 0 17.6 0s.725.267.978.8l4.489 8.885 10.016 1.425c.745.117 1.117.416 1.117.898z"/>
            </g>
        </svg>';

?>

<div class="checkout-success" id="checkout-success-kip">
    <?php if ($block->getOrderId()) : ?>
        <p id="ls-order-result"></p>
        <?php if ($block->getIsOrderStorePickup()->execute()) : ?>
            <p><?= $block->escapeHtml(__('We\'ll email you an order and pick-up confirmation with details.')) ?></p>
        <?php else : ?>
            <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
        <?php endif; ?>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <!--<div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
               href="<?/*= $block->escapeUrl($block->getContinueUrl()) */?>"><span><?/*= $block->escapeHtml(__('Continue Shopping')) */?></span></a>
        </div>
    </div>-->

    <div class="share-experience">
        <form id="share-experience" method="POST" action="/contact/index/post/">
            <input hidden name="name" value="<?= $kip->getCustomerName() ?>">
            <input hidden name="email" value="<?= $kip->getCustomerEmail() ?>">
            <input hidden name="telephone" value="<?= $kip->getCustomerTelephone() ?>">
            <?= $block->getBlockHtml('formkey') ?>
            <h3 class="medium-24">
                Ayúdanos a darte la mejor experiencia
            </h3>
            <p class="medium-14">
                Califica tu experiencia de uso:
            </p>
            <div class="stars">
                <p class="rate-star" data-rate="5">
                    <?= $star ?>
                </p>
                <p class="rate-star" data-rate="4">
                    <?= $star ?>
                </p>
                <p class="rate-star" data-rate="3">
                    <?= $star ?>
                </p>
                <p class="rate-star" data-rate="2">
                    <?= $star ?>
                </p>
                <p class="rate-star" data-rate="1">
                    <?= $star ?>
                </p>
            </div>
            <p class="medium-14">
                Algun comentario para ayudarnos a mejorar:
            </p>
            <textarea class="medium-14" name="comment" placeholder="Escribe aquí..."></textarea>
        </form>
        <div class="row">
            <a class="secondary-btn close-modal" href="/">
                <?= $block->escapeHtml(__('Ir al Inicio')) ?>
            </a>
            <button class="primary-btn" id="report" onclick="shareExperience(this)">
                <?= $block->escapeHtml(__('Enviar')) ?>
            </button>
        </div>
    </div>
</div>

<script type="text/javascript">

    let stars = [].slice.call(document.querySelectorAll('.rate-star'));
    stars.map(star => {
        star.addEventListener('click', function () {
            stars.map((l) => l.classList.remove('selected'));
            star.classList.add('selected')
        })
    })

    function shareExperience(button) {
        let f = new FormData(document.querySelector('#share-experience'));

        let rate = document.querySelector('.rate-star.selected')
        if (f && rate) {
            let data = '';
            for (let prop of f.entries()) {
                if (prop[0] && prop[1]) {
                    data += `${prop[0]}=`;
                    if(prop[0] === 'comment') {
                        data += `${encodeURI('Comentarios pedido ' + <?= $block->getOrderId() ?> + ': ' + prop[1] + ', estrellas: ' + rate.getAttribute('data-rate'))}&`;
                    } else {
                        data += `${encodeURI(prop[1])}&`;
                    }
                }
            }

            button.style.opacity = '0.5';
            ajax('POST',
                '/contact/index/post?' + data,
                null,
                'text/html; charset=UTF-8',
            ).then(function (response) {
                button.style.opacity = '1';
                let data = JSON.parse(response);
                if (data.status === 200) {
                    document.querySelector('.share-experience').innerHTML = '<p class="medium-14" style="text-align: center">Muchas gracias, con tus comentarios nos ayudas a ser mejores cada día.</p>'
                }
            })
        }
    }
</script>
