<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Helper\Address;

/** @var \Magento\Customer\Block\Form\Register $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/** @var Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $block->getData('addressHelper');
/** @var \Magento\Directory\Helper\Data $directoryHelper */
$directoryHelper = $block->getData('directoryHelper');
$formData = $block->getFormData();
?>
<?php $displayAll = $block->getConfig('general/region/display_all'); ?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<div class="block-title">
    <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */
        echo __('Crea tu cuenta') ?>
    </strong>
    <p>
        <?php /* @escapeNotVerified */
        echo __('¡Te estamos esperando!') ?>
    </p>
</div>
<form class="form create account form-create-account"
      action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
      method="post"
      id="signup-form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Personal Information')) ?></span></legend><br>
        <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">

        <?= ''/*$block->getLayout()
            ->createBlock(\Magento\Customer\Block\Widget\Name::class)
            ->setObject($formData)
            ->setForceUseCustomerAttributes(true)
            ->toHtml()*/ ?>

        <div class="field field-name-firstname required">
            <label class="label" for="firstname"><span>First Name</span></label>
            <div class="control">
                <input placeholder="<?= $escaper->escapeHtml(__('First Name')) ?>" maxlength="24" data-validate="{&quot;required&quot;:true,&quot;maxlength&quot;:30}" type="text" id="firstname" name="firstname" value="" title="First Name" class="input-text required-entry" autocomplete="off" aria-required="true">
            </div>
        </div>
        <div class="field field-name-lastname required">
            <label class="label" for="lastname"><span>Last Name</span></label>
            <div class="control">
                <input placeholder="<?= $escaper->escapeHtml(__('Last Name')) ?>" maxlength="24" data-validate="{&quot;required&quot;:true,&quot;maxlength&quot;:30}" type="text" id="lastname" name="lastname" value="" title="Last Name" class="input-text required-entry" autocomplete="off" aria-required="true">
            </div>
        </div>

        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="field choice newsletter">
                <input type="hidden"
                       name="is_subscribed"
                       title="<?= $escaper->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>"
                       value="1"
                       id="is_subscribed"
                       <?php if ($formData->getIsSubscribed()): ?>checked="checked"<?php endif; ?>
                       class="checkbox">
                <label for="is_subscribed" class="label">
                    <span><?= $escaper->escapeHtml(__('Sign Up for Newsletter')) ?></span>
                </label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?= $block->getChildHtml('customer.form.register.newsletter') ?>
        <?php endif ?>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= ''//$_dob->setDate($formData->getDob())->toHtml() ?>
            <div class="field date field-dob required">
                <label class="label" for="dob">
                    <span>Fecha de nacimiento</span>
                </label>
                <div class="control customer-dob">
                    <input type="text"
                           name="dob"
                           id="dob"
                           value=""
                           data-mage-init='{"validation":{}}'
                           data-validate="{'required-entry': true, 'validate-date-au': true}"
                           placeholder="Nacimiento (dd/mm/aaaa)"
                           autocomplete="on"
                           aria-required="true"
                           aria-invalid="true"
                    >
                </div>
            </div>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($formData->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($formData->getGender())->toHtml() ?>
        <?php endif ?>

        <?= $block->getChildHtml('fieldset_create_info_additional') ?>
    </fieldset>

    <?php if ($block->getShowAddressFields()): ?>
        <?php $cityValidationClass = $addressHelper->getAttributeValidationClass('city'); ?>
        <?php $postcodeValidationClass = $addressHelper->getAttributeValidationClass('postcode'); ?>
        <?php $regionValidationClass = $addressHelper->getAttributeValidationClass('region'); ?>
        <fieldset class="fieldset address">
            <legend class="legend"><span><?= $escaper->escapeHtml(__('Address Information')) ?></span></legend><br>
            <input type="hidden" name="create_address" value="1" />

            <?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
            <?php if ($_company->isEnabled()): ?>
                <?= $_company->setCompany($formData->getCompany())->toHtml() ?>
            <?php endif ?>

            <?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
            <?php if ($_telephone->isEnabled()): ?>
                <?= $_telephone->setTelephone($formData->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
            <?php if ($_fax->isEnabled()): ?>
                <?= $_fax->setFax($formData->getFax())->toHtml() ?>
            <?php endif ?>

            <?php
            $_streetValidationClass = $addressHelper->getAttributeValidationClass('street');
            ?>

            <div class="field street required">
                <label for="street_1" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="street[]"
                           value="<?= $escaper->escapeHtmlAttr($formData->getStreet(0)) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>"
                           id="street_1"
                           class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>">
                    <div class="nested">
                        <?php
                        $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass));
                        $streetLines = $addressHelper->getStreetLines();
                        ?>
                        <?php for ($_i = 2, $_n = $streetLines; $_i <= $_n; $_i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                    <span><?= $escaper->escapeHtml(__('Address')) ?></span>
                                </label>
                                <div class="control">
                                    <input type="text"
                                           name="street[]"
                                           value="<?= $escaper->escapeHtml($formData->getStreetLine($_i - 1)) ?>"
                                           title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $_i)) ?>"
                                           id="street_<?= /* @noEscape */ $_i ?>"
                                           class="input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass) ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
                </label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span>
                </label>
                <div class="control">
                    <select id="region_id"
                            name="region_id"
                            title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                            class="validate-select region_id">
                        <option value="">
                            <?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?>
                        </option>
                    </select>
                    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'select#region_id') ?>
                    <input type="text"
                           id="region"
                           name="region"
                           value="<?= $escaper->escapeHtml($block->getRegion()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                           class="input-text <?= $escaper->escapeHtmlAttr($regionValidationClass) ?>">
                    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'input#region') ?>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="city"
                           value="<?= $escaper->escapeHtmlAttr($formData->getCity()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                           class="input-text <?= $escaper->escapeHtmlAttr($cityValidationClass) ?>"
                           id="city">
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="postcode"
                           value="<?= $escaper->escapeHtmlAttr($formData->getPostcode()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                           id="zip"
                           class="input-text validate-zip-international
                            <?= $escaper->escapeHtmlAttr($postcodeValidationClass) ?>">
                </div>
            </div>

            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

    <?php endif; ?>

    <fieldset class="fieldset create account" data-hasrequired="<?= '' /*$escaper->escapeHtmlAttr(__('* Required Fields'))*/ ?>">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Sign-in Information')) ?></span></legend><br>
        <div class="field required">
            <label for="email_address" class="label"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input placeholder="<?= $escaper->escapeHtml(__('Email')) ?>"
                        type="email"
                       name="email"
                       autocomplete="email"
                       id="email_address"
                       value="<?= $escaper->escapeHtmlAttr($formData->getEmail()) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field telephone required">
            <label for="telephone" class="label">
                <span><?= $escaper->escapeHtml(__('Telephone')) ?></span>
            </label>
            <div class="control">
                <input placeholder="<?= $escaper->escapeHtml(__('Telephone')) ?>"
                       type="text"
                       name="telephone-preview"
                       title="<?= $escaper->escapeHtmlAttr(__('Telephone')) ?>"
                       id="telephone-preview"
                       class="input-text"
                       data-validate="{required:true}"
                       autocomplete="off">
                <input hidden name="telephone" id="telephone">
            </div>
        </div>
        <div class="field password required">
            <label for="password" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
            <div class="control">
                <input placeholder="<?= $escaper->escapeHtml(__('Password')) ?>"
                        type="password" name="password" id="password"
                       title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>"
                       class="input-text"
                       data-password-min-length="<?=
                       $escaper->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?=
                       $escaper->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $escaper->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $escaper->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>

        </div>
        <div class="field confirmation required">
            <label for="password-confirmation" class="label">
                <span><?= $escaper->escapeHtml(__('Confirm Password')) ?></span>
            </label>
            <div class="control">
                <input placeholder="<?= $escaper->escapeHtml(__('Confirm Password')) ?>"
                        type="password"
                       name="password_confirmation"
                       title="<?= $escaper->escapeHtmlAttr(__('Confirm Password')) ?>"
                       id="password-confirmation"
                       class="input-text"
                       data-validate="{required:true, equalTo:'#password'}"
                       autocomplete="off">
            </div>
        </div>
        <p class="medium-12 disclaimer">
            Al dar clic en “Crear cuenta”, acepta que ha leído y que acepta nuestra <a href="/terms?privacy" target="_blank">Política de Privacidad e Información</a> y nuestros <a href="/terms" target="_blank">Términos y Condiciones</a>.
        </p>
    </fieldset>

    <fieldset class="fieldset additional_info">
        <?= $block->getChildHtml('form_additional_info') ?>

        <div class="field choice terms required">
            <input type="hidden" name="kip_terms[0]" value="1" />
            <input type="checkbox"
                   name="kip_terms[0]"
                   value="1"
                   title="<?= $escaper->escapeHtmlAttr(__('Aceptar Términos & Condiciones')) ?>"
                   id="kip_terms"
                   class="checkbox"
                   checked
                   hidden
                   data-validate="{required:true}"
            >
            <label for="kip_terms" class="label checkbox">
                <span><?= $escaper->escapeHtmlAttr(__('Aceptar Términos & Condiciones'))?></span>
            </label>
        </div>

        <div class="field choice privacy required">
            <input type="hidden" name="kip_privacy[0]" value="1" />
            <input type="checkbox"
                   name="kip_privacy[0]"
                   value="1"
                   title="<?= $escaper->escapeHtmlAttr(__('Aceptar Política de Privacidad')) ?>"
                   id="kip_privacy"
                   class="checkbox"
                   checked
                   hidden
                   data-validate="{required:true}"
            >
            <label for="kip_terms" class="label checkbox">
                <span><?= $escaper->escapeHtml(__('Aceptar Política de Privacidad')) ?></span>
            </label>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action submit primary"
                    title="<?= $escaper->escapeHtmlAttr(__('Create an Account')) ?>">
                <span><?= $escaper->escapeHtml(__('Create an Account')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back"
               href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Back')) ?></span>
            </a>
        </div>
    </div>
</form>
<?php $ignore = /* @noEscape */ false /*$_dob->isEnabled()*/ ? '\'input[id$="full"]\'' : 'null';
$scriptString = <<<script
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#signup-form-validate');
    var ignore = {$ignore};

    dataForm.mage('validation', {
script;
if (false /*$_dob->isEnabled()*/):
    $scriptString .= <<<script
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
script;
else:
    $scriptString .= <<<script
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
script;
endif;
$scriptString .= <<<script
    }).find('input:text').attr('autocomplete', 'off');
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php if ($block->getShowAddressFields()): ?>
    <?php
    $regionJson = /* @noEscape */ $directoryHelper->getRegionJson();
    $regionId = (int) $formData->getRegionId();
    $countriesWithOptionalZip = /* @noEscape */ $directoryHelper->getCountriesWithOptionalZip(true);
    ?>
    <script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $displayAll ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#signup-form-validate",
                "regionJson": {$regionJson},
                "defaultRegion": "{$regionId}",
                "countriesWithOptionalZip": {$countriesWithOptionalZip}
            }
        }
    }
</script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>

<script type="text/javascript">
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        let tel = document.querySelector("#telephone-preview"),
            telSubmit = document.querySelector("#telephone"),
            iti = window.intlTelInput(tel, ({
                preferredCountries: ['sv'],
                initialCountry: 'sv',
                separateDialCode: true
            }));

        function bindPhones() {
            let country = iti.getSelectedCountryData();
            telSubmit.value = `+${country.dialCode} ${tel.value}`;
        }

        tel.addEventListener("countrychange", bindPhones);
        tel.addEventListener("keydown", bindPhones);
        tel.addEventListener("keyup", bindPhones);

        // VALIDATION
        $('#signup-form-validate').submit(function() {  
        //DATALAYER-CODITY
        window.dataLayer.push({'event': 'register'});

        var phonex = document.getElementById('telephone-preview');
        var areaCode = document.getElementsByClassName('iti__selected-dial-code');
        var allValue = areaCode[0].innerText+phonex.value;     
        if (phonex.value.length>6 && areaCode[0].innerText.length>2){               
            window.localStorage.setItem('xlm_lphone', allValue);    
            window.localStorage.setItem('p', allValue);               
            window.localStorage.removeItem('lastShowed');   
            var xhr = new XMLHttpRequest();
            var apiURL = "https://kip-logistic-api.azurewebsites.net/req_verify";
            xhr.open("POST", apiURL, true);
            xhr.setRequestHeader('Content-Type', 'application/json');
            xhr.send(JSON.stringify({
                p: allValue
            }));            
        }
        return true;
        });

    });
</script>
