<?php
/** @var \Bananacode\Kip\Block\Adminhtml\System\Config\Button $block */

?>

<div class="actions actions-validate-vat">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="if(confirm('¿Sobrescribir árboles de categorías?')) window.location.href= document.getElementById('<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>').getAttribute('data-url'); else return false;"
            class="action-validate-vat primary" type="button"
            data-url="<?= $block->escapeHtmlAttr($block->getButtonUrl()) ?>"
            id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
