<script type="text/template" id="instant-stats-template">
    {{#hasOneResult}}<strong>1</strong> <?php echo $block->escapeHtml(__('result')); ?> encontrado{{/hasOneResult}}

    {{#hasManyResults}}
    {{^hasNoResults}}{{first}}-{{last}} de{{/hasNoResults}}
    <strong>
        <span itemprop="numberOfItems">{{nbHits}}</span>
        <?php echo $block->escapeHtml(__('results found')); ?>
    </strong>
    {{/hasManyResults}}

    {{^hasNoResults}}
    <?php echo $block->escapeHtml(__('in')); ?> {{seconds}} <?php echo $block->escapeHtml(__('seconds')); ?>
    {{/hasNoResults}}
</script>
