<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\Order\DefaultOrder */

/** @var $_item \Magento\Sales\Model\Order\Item\Interceptor */
$_item = $block->getItem();

/**
 * @var \Bananacode\Kip\Block\Main $kip
 */
$kip = $block->getLayout()->createBlock('Bananacode\Kip\Block\Main');

$invoicedItem = $kip->getLsInvoicedItem($_item->getOrder()->getDocumentId(), $_item->getSku());

?>

<tr>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <?php $presentacion = $kip->getPresentacion($_item->getProductId(), true, [], true); ?>
        <p class="sku"><?= $block->escapeHtml(is_string($presentacion) ? $presentacion : $_item->getSku()) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                    <dd>
                        <?= /* @noEscape */ nl2br($block->escapeHtml($option['value'])) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty">
        <?= $_item->getQtyOrdered() > 0 ? 'Pedido: ' . number_format(floatval($_item->getQtyOrdered()), 2) : '' ?>
        <?= $invoicedItem['qty'] >= 0 ? '<br/>Facturado: ' . number_format(floatval($invoicedItem['qty']), 2) : '' ?>
    </td>
    <td class="item-price">
        <p>
            <?= /* @noEscape */
                //$block->getItemPrice($_item)
                '$' . number_format($_item->getPrice(), 2)/* + $_item->getDiscountAmount()*/
            ?>
        </p>
        <?= $invoicedItem['qty'] >= 0 ? ('<br/>' . $kip->formatValue($invoicedItem['amount'])) : '' ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
) : ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br/><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br/><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br/><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
