<?php
// @codingStandardsIgnoreFile
/** @var  $block History */
$_orders    = $block->getOrderHistory();
$orderExist = false;

use \Ls\Customer\Block\Order\History;
use \Ls\Omni\Client\Ecommerce\Entity\ArrayOfSalesEntry;
use Magento\Framework\Data\Helper\PostHelper; ?>
<div class="breadcrumbs">
    <ul class="items">
        <li>
            <a href="/customer/account">
                <?= $block->escapeHtmlAttr(__('Configuración de cuenta')) ?>
            </a>
        </li>
        <li>
            <a href="#">
                <?= $block->escapeHtmlAttr(__('Mis Pedidos')) ?>
            </a>
        </li>
    </ul>
</div>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders): ?>
    <?php
    if ($_orders instanceof ArrayOfSalesEntry) {
        $_orders = $_orders->getSalesEntry();
        if (count($_orders) > 0) {
            $orderExist = true; ?>
            <div class="table-wrapper orders-history" id="my-orders-table-container" style="display:none;">
                <h1 class="bold-24">
                    <?= __('Mis pedidos') ?>
                </h1>
                <table class="data table table-order-items history" id="my-orders-table" style="width:100%">
                    <caption class="table-caption"><?= /* @escapeNotVerified */
                        __('Orders') ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col id"><?= /* @escapeNotVerified */
                            __('Doc ID') ?></th>
                        <th scope="col" class="col date"><?= /* @escapeNotVerified */
                            __('Date') ?></th>
                        <th scope="col" class="col shipping"><?= /* @escapeNotVerified */
                            __('Ship To') ?></th>
                        <!--<th scope="col" class="col store-name"><?/*=
                            __('Store Name') */?></th>-->
                        <th scope="col" class="col total"><?= /* @escapeNotVerified */
                            __('Total') ?></th>
                        <th scope="col" class="col status"><?= /* @escapeNotVerified */
                            __('Status') ?></th>
                        <th scope="col" class="col actions"><?= /* @escapeNotVerified */
                            __('Action') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($_orders as $_order):
                        $magOrder = $block->getOrderByDocumentId($_order);
                    ?>
                        <tr>
                            <td data-th="<?= $block->escapeHtml(__('Document ID #')) ?>" class="col id">
                                <?= /* @escapeNotVerified */ /*$_order->getId() . ' | ' . */$_order->getCustomerOrderNo() ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Date')) ?>"
                                class="col date">
                                <span style="display:none;"><?= strtotime($_order->getDocumentRegTime())?></span>
                                <?= /* @escapeNotVerified */
                                $block->getFormattedDate($_order->getDocumentRegTime()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>"
                                class="col shipping"><?= $_order->getShipToName() ? $block->escapeHtml($_order->getShipToName()) : __('Not Applicable') ?></td>
                            <!--<td data-th="<?/*= $block->escapeHtml(__('Store Name')) */?>"
                                class="col store-name"><?/*= $_order->getStoreName() */?></td>-->
                            <td data-th="<?= $block->escapeHtml(__('Total')) ?>"
                                class="col total"><?= /* @escapeNotVerified */
                                $block->getFormattedPrice($_order->getTotalAmount()) ?></td>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status <?= strtolower($_order->getStatus()) ?>">
                                <?= /* @escapeNotVerified */
                                __($_order->getStatus()) ?>
                            </td>
                            <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                <a href="<?= /* @escapeNotVerified */
                                $block->getViewUrl($_order, $magOrder) ?>" class="action view">
                                <span><?= /* @escapeNotVerified */
                                    __('Detalles') ?></span>
                                </a>
                                <?php
                                if (!empty($magOrder)):
                                    if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($magOrder->getEntityId())) : ?>
                                        <a href="#" data-post='<?php /* @escapeNotVerified */
                                        echo
                                        $this->helper(PostHelper::class)
                                            ->getPostData($block->getReorderUrl($magOrder))
                                        ?>' class="action order">
                                        <span><?= /* @escapeNotVerified */
                                            __('Reorder') ?></span>
                                        </a>
                                    <?php endif;
            endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php
        }
    } else {
        $orderExist = true; ?>
        <div class="table-wrapper orders-history" id="my-orders-table-container" style="display:none;">
            <table class="data table table-order-items history" id="my-orders-table" style="width:100%">
                <caption class="table-caption"><?= /* @escapeNotVerified */
                    __('Orders') ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */
                        __('Doc ID') ?></th>
                    <th scope="col" class="col date"><?= /* @escapeNotVerified */
                        __('Date') ?></th>
                    <?= /* @noEscape */
                    $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= /* @escapeNotVerified */
                        __('Ship To') ?></th>
                    <th scope="col" class="col total"><?= /* @escapeNotVerified */
                        __('Total') ?></th>
                    <th scope="col" class="col status"><?= /* @escapeNotVerified */
                        __('Status') ?></th>
                    <th scope="col" class="col actions"><?= /* @escapeNotVerified */
                        __('Action') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>"
                            class="col id"><?= /* @escapeNotVerified */
                            $_order->getRealOrderId() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>"
                            class="col date"><?= /* @escapeNotVerified */
                            $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= /* @noEscape */
                            $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>"
                            class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : __('Not Applicable') ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Total')) ?>"
                            class="col total"><?= /* @escapeNotVerified */
                            $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>"
                            class="col status <?= strtolower($_order->getStatus()) ?>"><?= /* @escapeNotVerified */
                            $_order->getStatusLabel() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= /* @escapeNotVerified */
                            $block->getViewUrl($_order) ?>" class="action view">
                                <span><?= /* @escapeNotVerified */
                                    __('Detalles') ?></span>
                            </a>
                            <?php
                            if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getId())) : ?>
                                <a href="#" data-post='<?php /* @escapeNotVerified */
                                echo
                                $this->helper(PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= /* @escapeNotVerified */
                                        __('Reorder') ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php
    } ?>
    <script type="text/javascript">
        require(['jquery', 'Ls_Core/js/datatables.min'], function($, $t){
            $(document).ready(function() {
                $('#my-orders-table thead tr').clone(true).appendTo( '#my-orders-table thead' );

                $('#my-orders-table thead tr:eq(1) th').each( function (i) {
                    var title = $(this).text();
                    $(this).html( '<input type="text" placeholder="Buscar" />' );
                    $( 'input', this ).on( 'keyup change', function () {
                        if ( table.column(i).search() !== this.value ) {
                            table
                                .column(i)
                                .search( this.value )
                                .draw();
                        }
                    } );
                } );

                var table = $('#my-orders-table').DataTable({
                    order: [[1, 'desc']],
                    orderCellsTop: true,
                    language: {
                        "processing": "Procesando...",
                        "lengthMenu": "Mostrar _MENU_ registros",
                        "zeroRecords": "No se encontraron resultados",
                        "emptyTable": "Ningún dato disponible en esta tabla",
                        "infoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                        "infoFiltered": "(filtrado de un total de _MAX_ registros)",
                        "search": "Buscar:",
                        "infoThousands": ",",
                        "loadingRecords": "Cargando...",
                        "paginate": {
                            "first": "Primero",
                            "last": "Último",
                            "next": "Siguiente",
                            "previous": "Anterior"
                        },
                        "aria": {
                            "sortAscending": ": Activar para ordenar la columna de manera ascendente",
                            "sortDescending": ": Activar para ordenar la columna de manera descendente"
                        },
                        "buttons": {
                            "copy": "Copiar",
                            "colvis": "Visibilidad",
                            "collection": "Colección",
                            "colvisRestore": "Restaurar visibilidad",
                            "copyKeys": "Presione ctrl o u2318 + C para copiar los datos de la tabla al portapapeles del sistema. <br \/> <br \/> Para cancelar, haga clic en este mensaje o presione escape.",
                            "copySuccess": {
                                "1": "Copiada 1 fila al portapapeles",
                                "_": "Copiadas %d fila al portapapeles"
                            },
                            "copyTitle": "Copiar al portapapeles",
                            "csv": "CSV",
                            "excel": "Excel",
                            "pageLength": {
                                "-1": "Mostrar todas las filas",
                                "1": "Mostrar 1 fila",
                                "_": "Mostrar %d filas"
                            },
                            "pdf": "PDF",
                            "print": "Imprimir"
                        },
                        "autoFill": {
                            "cancel": "Cancelar",
                            "fill": "Rellene todas las celdas con <i>%d<\/i>",
                            "fillHorizontal": "Rellenar celdas horizontalmente",
                            "fillVertical": "Rellenar celdas verticalmentemente"
                        },
                        "decimal": ",",
                        "searchBuilder": {
                            "add": "Añadir condición",
                            "button": {
                                "0": "Constructor de búsqueda",
                                "_": "Constructor de búsqueda (%d)"
                            },
                            "clearAll": "Borrar todo",
                            "condition": "Condición",
                            "conditions": {
                                "date": {
                                    "after": "Despues",
                                    "before": "Antes",
                                    "between": "Entre",
                                    "empty": "Vacío",
                                    "equals": "Igual a",
                                    "notBetween": "No entre",
                                    "notEmpty": "No Vacio",
                                    "not": "Diferente de"
                                },
                                "number": {
                                    "between": "Entre",
                                    "empty": "Vacio",
                                    "equals": "Igual a",
                                    "gt": "Mayor a",
                                    "gte": "Mayor o igual a",
                                    "lt": "Menor que",
                                    "lte": "Menor o igual que",
                                    "notBetween": "No entre",
                                    "notEmpty": "No vacío",
                                    "not": "Diferente de"
                                },
                                "string": {
                                    "contains": "Contiene",
                                    "empty": "Vacío",
                                    "endsWith": "Termina en",
                                    "equals": "Igual a",
                                    "notEmpty": "No Vacio",
                                    "startsWith": "Empieza con",
                                    "not": "Diferente de"
                                },
                                "array": {
                                    "not": "Diferente de",
                                    "equals": "Igual",
                                    "empty": "Vacío",
                                    "contains": "Contiene",
                                    "notEmpty": "No Vacío",
                                    "without": "Sin"
                                }
                            },
                            "data": "Data",
                            "deleteTitle": "Eliminar regla de filtrado",
                            "leftTitle": "Criterios anulados",
                            "logicAnd": "Y",
                            "logicOr": "O",
                            "rightTitle": "Criterios de sangría",
                            "title": {
                                "0": "Constructor de búsqueda",
                                "_": "Constructor de búsqueda (%d)"
                            },
                            "value": "Valor"
                        },
                        "searchPanes": {
                            "clearMessage": "Borrar todo",
                            "collapse": {
                                "0": "Paneles de búsqueda",
                                "_": "Paneles de búsqueda (%d)"
                            },
                            "count": "{total}",
                            "countFiltered": "{shown} ({total})",
                            "emptyPanes": "Sin paneles de búsqueda",
                            "loadMessage": "Cargando paneles de búsqueda",
                            "title": "Filtros Activos - %d"
                        },
                        "select": {
                            "1": "%d fila seleccionada",
                            "_": "%d filas seleccionadas",
                            "cells": {
                                "1": "1 celda seleccionada",
                                "_": "$d celdas seleccionadas"
                            },
                            "columns": {
                                "1": "1 columna seleccionada",
                                "_": "%d columnas seleccionadas"
                            }
                        },
                        "thousands": ".",
                        "datetime": {
                            "previous": "Anterior",
                            "next": "Proximo",
                            "hours": "Horas",
                            "minutes": "Minutos",
                            "seconds": "Segundos",
                            "unknown": "-",
                            "amPm": [
                                "am",
                                "pm"
                            ]
                        },
                        "editor": {
                            "close": "Cerrar",
                            "create": {
                                "button": "Nuevo",
                                "title": "Crear Nuevo Registro",
                                "submit": "Crear"
                            },
                            "edit": {
                                "button": "Editar",
                                "title": "Editar Registro",
                                "submit": "Actualizar"
                            },
                            "remove": {
                                "button": "Eliminar",
                                "title": "Eliminar Registro",
                                "submit": "Eliminar",
                                "confirm": {
                                    "_": "¿Está seguro que desea eliminar %d filas?",
                                    "1": "¿Está seguro que desea eliminar 1 fila?"
                                }
                            },
                            "error": {
                                "system": "Ha ocurrido un error en el sistema (<a target=\"\\\" rel=\"\\ nofollow\" href=\"\\\">Más información&lt;\\\/a&gt;).<\/a>"
                            },
                            "multi": {
                                "title": "Múltiples Valores",
                                "info": "Los elementos seleccionados contienen diferentes valores para este registro. Para editar y establecer todos los elementos de este registro con el mismo valor, hacer click o tap aquí, de lo contrario conservarán sus valores individuales.",
                                "restore": "Deshacer Cambios",
                                "noMulti": "Este registro puede ser editado individualmente, pero no como parte de un grupo."
                            }
                        },
                        "info": "Mostrando de _START_ a _END_ de _TOTAL_ entradas"
                    }
                });

                $('#my-orders-table-container').show();
            } );
        })
    </script>
<?php
endif;
?>
<?php if ($orderExist == false) { ?>
    <div class="message info empty">
        <h1 class="bold-24">
            <?= __('Mis pedidos') ?>
        </h1>
        <div class="content">
            <p class="medium-16">
                <?= __('No haz realizado ninguna orden ') ?>
            </p>
            <a href="/" class="action-secondary">
                <?= __('Empieza a comprar') ?>
            </a>
        </div>
    </div>
<?php } ?>
