<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
$_category  = $block->getCurrentCategory();
$_imgHtml   = '';

/**
 * @var \Bananacode\Kip\Block\Main $kip
 */
$kip = $block->getLayout()->createBlock('Bananacode\Kip\Block\Main');

if ($_imgUrl = $block->getImage()->getUrl($_category)) {
    $_imgHtml = '<div class="category-image"><img class="lazy-load-img" data-src="'
        . $block->escapeUrl($_imgUrl)
        . '" alt="'
        . $block->escapeHtmlAttr($_category->getName())
        . '" title="'
        . $block->escapeHtmlAttr($_category->getName())
        . '" class="image" /></div>';
    $_imgHtml = $block->getOutput()->categoryAttribute($_category, $_imgHtml, 'image');
    /* @noEscape */ echo $_imgHtml;
}
?>

<?php if ((!empty($_imgHtml) || $_category->getIncludeInMenu()) && !$kip->isRecipe()): ?>
    <h2 class="parent-category-title">
        <?= $_category->getParentCategory()->getName() ?>
    </h2>

    <div class="shadow"></div>

    <script>
        let categoryView = document.querySelector('#maincontent .category-view');
        categoryView ? categoryView.classList.add('image') : '';

        let title = document.querySelector('#maincontent .page-title-wrapper');
        title ? title.classList.add('image') : '';
    </script>
<?php else: ?>
    <?php if ($kip->isRecipe()): ?>
        <script>
            let body = document.querySelector('body');
            body ? body.classList.add('kip-recipes-pcp') : '';
            body ? body.classList.add('no-shopping') : '';
        </script>
    <?php endif; ?>
<?php endif; ?>
