<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Sales\Block\Adminhtml\Order\Create\Data $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

?>

<div class="page-create-order">
    <?php $scriptString = <<<script
    require(["Magento_Sales/order/create/form"], function(){
        order.setCurrencySymbol('{$block->escapeJs($block->getCurrencySymbol($block->getCurrentCurrencyCode()))}')
    });
    script;
    ?>

    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

    <div class="order-details<?php if ($block->getCustomerId()): ?> order-details-existing-customer<?php endif; ?>">

        <div id="order-additional_area" class="admin__page-section order-additional-area">
            <?= $block->getChildHtml('additional_area') ?>
        </div>
        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
            'display:none',
            'div#order-additional_area'
        ) ?>

        <div id="order-search" class="admin__page-section order-search-items no-display">
            <?= $block->getChildHtml('search') ?>
        </div>
        <?= /* @noEscape */ $secureRenderer->renderTag(
            'script',
            [],
            "var elemOrderSearch = document.querySelector('div#order-search');
            if (elemOrderSearch) {
                elemOrderSearch.style.display = 'none';
                elemOrderSearch.classList.remove('no-display');
            }",
            false
        ) ?>

        <section id="order-items" class="admin__page-section order-items" data-mage-init='{"loader": {}}'>
            <?= $block->getChildHtml('items') ?>
        </section>

        <div id="order-errors" class="order-errors"><?= $block->getChildHtml('errors') ?></div>

        <section id="order-form_account" class="admin__page-section order-account-information">
            <?= $block->getChildHtml('form_account') ?>
        </section>

        <section id="order-addresses" class="admin__page-section order-addresses">
            <div class="admin__page-section-title">
                <span class="title"><?= $block->escapeHtml(__('Address Information')) ?></span>
            </div>
            <div class="admin__page-section-content">
                <div id="order-billing_address" class="admin__page-section-item order-billing-address">
                    <?= $block->getChildHtml('billing_address') ?>
                </div>
                <div id="order-shipping_address" class="admin__page-section-item order-shipping-address">
                    <?= $block->getChildHtml('shipping_address') ?>
                </div>
            </div>
        </section>

        <section id="order-methods" class="admin__page-section order-methods">
            <div class="admin__page-section-title">
                <span class="title"><?= $block->escapeHtml(__('Payment &amp; Shipping Information'))?></span>
            </div>
            <div class="admin__page-section-content">
                <div id="order-billing_method" class="admin__page-section-item order-billing-method">
                    <?= $block->getChildHtml('billing_method') ?>
                </div>
                <div id="order-shipping_method" class="admin__page-section-item order-shipping-method">
                    <?= $block->getChildHtml('shipping_method') ?>
                </div>

                <div class="admin__page-section-item kip_data" style="width: 100%; float: left; margin-top: 20px">
                    <div class="admin__page-section-title">
                        <span class="title"><?= $block->escapeHtml(__('Kip'))?></span>
                        <input hidden id="kip_form_key" value="<?= $block->getRequest()->getCookie('PHPSESSID') ?>">
                        <input hidden id="kip_customer_id" value="<?= $block->getCustomerId() ?>">
                    </div>
                    <div id="scheduled">
                        <p><strong>Tiempo de entrega (programado | mismo día)</strong></p>
                        <select id="scheduled-date">
                            <option value="">Fecha de entrega</option>
                        </select>
                        <select id="scheduled-hours">
                            <option value="">Horas disponibles</option>
                        </select>
                    </div>
                    <div id="scheduled_festivity">
                        <p><strong>Tiempo de entrega (pre-order)</strong></p>
                        <select id="scheduled-date">
                            <option value="">Fecha de entrega</option>
                        </select>
                        <select id="scheduled-hours">
                            <option value="">Horas disponibles</option>
                        </select>
                    </div>
                    <br/>
                    <div id="packaging">
                        <p><strong>Selecciona el empaque del pedido</strong></p>
                        <select id="packaging-select">
                            <option value="">
                                Seleccionar
                            </option>
                            <option value="no-package">
                                Sin empaque
                            </option>
                            <option value="package">
                                Bolsas plásticas
                            </option>
                        </select>
                    </div>
                    <br/>
                    <div id="order-note">
                        <p><strong>Agregar nota</strong></p>
                        <textarea style="width: 100%" placeholder="Escribe aquí..."></textarea>
                        <p>Máximo 140 caracteres</p>
                    </div>
                    <br/>
                    <div id="tax-documents">
                        <p><strong>Documento Fiscal</strong></p>
                        <p class="medium-14">Seleccione el tipo de documento</p>
                        <select id="documents-types">
                            <option value="">Seleccionar</option>
                            <option value="FCF">Factura</option>
                            <option value="CCF">Crédito Fiscal</option>
                            <option value="EIVA">Exento de IVA</option>
                        </select>
                        <div id="stored-tax-docs">
                            <p class="medium-14">Datos guardados anteriormente del cliente.</p>
                            <select id="customer-documents">
                                <option value="" >Selecciona un documento fiscal</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <?php if ($block->getChildBlock('card_validation')): ?>
            <section id="order-card_validation" class="admin__page-section order-card-validation">
                <?= $block->getChildHtml('card_validation') ?>
            </section>
        <?php endif; ?>

        <?= $block->getChildHtml('gift_options') ?>

        <section class="admin__page-section order-summary">
            <div class="admin__page-section-title">
                <span class="title"><?= $block->escapeHtml(__('Order Total')) ?></span>
            </div>
            <div class="admin__page-section-content">
                <fieldset class="admin__fieldset order-history" id="order-comment">
                    <legend class="admin__legend"><span><?= $block->escapeHtml(__('Order History')) ?></span></legend>
                    <br>
                    <?= $block->getChildHtml('comment') ?>
                </fieldset>
                <fieldset id="order-totals" class="admin__fieldset order-totals">
                    <?= $block->getChildHtml('totals') ?>
                </fieldset>
            </div>
        </section>
    </div>

    <?php if ($block->getCustomerId()): ?>
        <div class="order-sidebar">
            <div class="store-switcher order-currency">
                <label class="admin__field-label" for="currency_switcher">
                    <?= $block->escapeHtml(__('Order Currency:')) ?>
                </label>
                <select id="currency_switcher"
                        class="admin__control-select"
                        name="order[currency]">
                    <?php foreach ($block->getAvailableCurrencies() as $_code): ?>
                        <option value="<?= $block->escapeHtmlAttr($_code) ?>"
                            <?php if ($_code == $block->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>
                                symbol="<?= $block->escapeHtmlAttr($block->getCurrencySymbol($_code)) ?>">
                            <?= $block->escapeHtml($block->getCurrencyName($_code)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'onchange',
                    "order.setCurrencyId(this.value);
                     order.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));",
                    'select#currency_switcher'
                ) ?>
            </div>
            <div class="customer-current-activity" id="order-sidebar">
                <?= $block->getChildHtml('sidebar') ?>
            </div>
        </div>
    <?php endif; ?>
</div>
