<?php
// @codingStandardsIgnoreFile
/**
 * @var  Ls\Omni\ViewModel\CouponsViewModel $viewModel
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$viewModel = $objectManager->create('\Ls\Omni\ViewModel\CouponsViewModel');
if ($viewModel->isCouponsEnabled() == "1") : ?>
    <div class="block discount" id="block-discount">
        <div class="content active" data-role="content" aria-labelledby="block-discount-heading">
            <form id="discount-coupon-form"
                  action="<?= /* @escapeNotVerified */
                  $block->getUrl('checkout/cart/couponPost') ?>"
                  method="post"
                  data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
                <input type="hidden" name="remove" id="remove-coupon" value="0"/>

                <div class="fieldset coupon<?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                    <div class="field">
                        <label for="coupon_code" class="label"><span><?= /* @escapeNotVerified */
                                __('Enter discount code') ?></span></label>
                        <div class="control">
                            <input type="text" class="input-text" id="coupon_code" name="coupon_code"
                                   value="<?= $block->escapeHtml($block->getCouponCode()) ?>"
                                   placeholder="<?= $block->escapeHtml(__('Enter discount code')) ?>" <?php if (strlen($block->getCouponCode())): ?> disabled="disabled" <?php endif; ?> />
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <?php if (!strlen($block->getCouponCode())): ?>
                            <div class="primary">
                                <button class="action apply primary" type="button" value="<?= /* @escapeNotVerified */
                                __('Apply Discount') ?>">
                                <span><?= /* @escapeNotVerified */
                                    __('Apply Discount') ?></span>
                                </button>
                            </div>
                        <?php else: ?>
                            <div class="primary">
                                <button type="button" class="action cancel primary" value="<?= /* @escapeNotVerified */
                                __('Cancel Coupon') ?>"><span><?= /* @escapeNotVerified */
                                        __('Cancel Coupon') ?></span></button>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </form>
            <?php
            echo '';/*$this->getLayout()
                ->createBlock('Ls\Omni\Block\Cart\Coupons')
                ->setTemplate('Ls_Omni::cart/coupons-loader.phtml')
                ->toHtml()*/
            ?>
        </div>
    </div>

    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function ($) {
            $(document).ready(function () {
                $(document).on("change", '#my_radio_box', function () {
                    var selected_value = $("input[name='group1']:checked").val();
                    var ele = $("input[name='group1']:checked");
                    ele.parent().siblings().removeClass('active');
                    ele.parent().addClass('active');
                    $("#coupon_code").val(selected_value);
                });
                $(document).on("click", ".available-coupons .coupon-major", function () {
                    $(this).find('input').attr('checked', 'checked');
                    $('#my_radio_box').change();
                });
            });
        });
    </script>
<?php
endif;
?>
